# Generated by Django 3.2.9 on 2021-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_alter_studentinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villages', models.CharField(max_length=30)),
            ],
        ),
    ]
