# Generated by Django 3.2.9 on 2021-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_auto_20211126_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogaccomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodations', models.CharField(max_length=255)),
            ],
        ),
    ]
