# Generated by Django 3.2.9 on 2021-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_blogaccomodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogtransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportations', models.CharField(max_length=255)),
            ],
        ),
    ]
