# Generated by Django 3.2.9 on 2021-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_blogtransportation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
    ]
