# Generated by Django 3.2.9 on 2021-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0007_blogname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
