# Generated by Django 3.2.9 on 2021-12-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0009_auto_20211224_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameee', models.CharField(max_length=55)),
                ('surnnameee', models.CharField(max_length=55)),
            ],
        ),
    ]
