# Generated by Django 3.2.9 on 2021-12-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0011_auto_20211225_0423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogaccomodation',
        ),
        migrations.DeleteModel(
            name='Blogtext',
        ),
        migrations.DeleteModel(
            name='Blogtransportation',
        ),
        migrations.DeleteModel(
            name='Blogvillage',
        ),
        migrations.RenameField(
            model_name='blogname',
            old_name='surrname',
            new_name='villages',
        ),
        migrations.AddField(
            model_name='blogname',
            name='accomodations',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogname',
            name='text',
            field=models.CharField(default=255, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogname',
            name='transportations',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
    ]
