# Generated by Django 3.2.9 on 2021-12-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_auto_20211225_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogname',
            name='name',
        ),
    ]
