# Generated by Django 3.2.9 on 2021-12-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0013_remove_blogname_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogname',
            new_name='Blogdetails',
        ),
    ]
